### PR TITLE
Use "modification time" instead of "creation time" on Windows

### PR DESCRIPTION
**Pull request by monsieurgustav**

### CODE REVIEW

**Comment by FlorianReimold** [comment]
Thank's for the PR! I will take a look, but it may take me some time. Please be patient ;-)

**Comment by FlorianReimold** [comment]
Short status update: Yes, this was a bug, thanks for reporting and fixing. The bug however must be fixed for Non-Windows platforms as well.

**Comment by monsieurgustav** [comment]
Yes, I only work on Windows ATM and I generally don't make change I cannot test...
But it's quite basic here, so I pushed the fix for all platforms. 🤞

**Comment by FlorianReimold** [comment]
I will test it out on other plattforms as well and then and merge it! I am not sure, but I think that also returning the localtime is not entirely correct. I think, fineftp should use the UTC here, as the client has no way of knowing the local timezone.

**Pull request merged**
